version: "2"

services:
  pihole:
    container_name: pihole
    image: jd10nn3/pihole-unbound:${VERSION}
    hostname: pihole
    domainname: pihole.local
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
      DNSSEC: "true"
      # Values used to communicate with the Unbound server
      DNS1: 127.0.0.1#5335
      DNS2: 127.0.0.1#5335
    # Volumes store your data between container upgrades
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole-unbound_dnsmasq:/etc/dnsmasq.d:rw
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
volumes:
  etc_pihole-unbound:
  etc_pihole-unbound_dnsmasq:
